

# These settings are for development mode only, override them in production by creating config/settings/sensitive_data.yml
#
# -- start of sensitive configuration settings --

sensitive:
  session:
    secret_token: 'b1fa7708e5775f3288307dbb64ba56b87632cff551fe520bd657d2da8f9184af1bc58b08d751743f7f8ec1a6a21e8b89202729bb2cdb11e261f45b4a54fb21db'

  facebook:
    app_id: '228136253935037'
    secret_key: '60650fb1ac90be47e76defd2f1bba24f'

  vkontakte:
    app_id: '2757507'
    secret_key: 'EGLTafWA7vi0P2iEBY9U'

# -- end of sensitive configuration settings --
